# application-dev.yml
variable:
  profiles: dev
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easyshop_dev?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  #热部署生效(true为开启，false为不开启，开发者根据喜好选择是否开启)
  devtools:
    restart:
      enabled: true